name: create Abfallbehaelter

on:
  workflow_dispatch:
    
jobs:
  defaultAction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Install Blender
      - name: Install Blender
        run: sudo snap install blender --classic
      # install gitpython
      - name: install gitpython
        run: pip install gitpython
      # export .obj
      - name: export .obj
        run: blender --background --python utilities/scripts/exportOBJ_Abfallbehaelter.py
      # render Thumbnails
      - name: Render Thumbnails
        run: blender --background --python utilities/scripts/renderThumbnail_Abfallbehaelter.py
      # create Readme
      - name: create Readme
        run: python utilities/scripts/createReadme_Abfallbehaelter.py
      # commit changes
      - name: commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated"
          git push
