name: createThumbnails_Ausleger

on:
  push:
    paths:
      - "Beleuchtung/Ausleger/**"
    
jobs:
  createThumbnails:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Install Blender
      - name: Install Blender
        run: sudo snap install blender --classic
      # install gitpython
      - name: install gitpython
        run: pip install gitpython
      # export .obj
      - name: export .obj
        run: blender --background --python utilities/scripts/exportOBJ_Ausleger.py
      # render Thumbnails
      - name: Render Thumbnails
        run: blender --background --python utilities/scripts/renderThumbnail_Ausleger.py
      # create Readme
      - name: create Readme
        run: python createReadme_Ausleger.py
      # commit changes
      - name: commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
