name: create Readme

on:
  push:
  workflow_dispatch:

jobs:
  # creates texured .obj files and creates a release
  defaultAction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # create Readme
      - name: create Readme
        run: python utilities/scripts/createReadme.py
      # commit changes
      - name: commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated"
          git push

  
