name: bot 
####
on:
  push:
    branches: [ main ]
jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        uses: snow-actions/tweet@v1.4.0
        with:
          status: This is a Test
        env:
          CONSUMER_API_KEY: ${{ secrets.API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          