name: bot
# This is a basic workflow to help you get started with Actionsname: TwitterBot# Controls when the action will run. 
on:
  push:
    branches: [ main ]
jobs:
 # This workflow contains a single job called “build”
  build:
 # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Tweet
        uses: snow-actions/tweet@v1.4.0
        with:
          status: This is a Test
        env:
          CONSUMER_API_KEY: ${{ secrets.API_KEY }}
          CONSUMER_API_SECRET_KEY: ${{ secrets.API_KEY_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN}}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          