name: bot
# This is a basic workflow to help you get started with Actionsname: TwitterBot# Controls when the action will run. 
on:
  push:
    branches: [ main ]
jobs:
 # This workflow contains a single job called “build”
  build:
 # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
 #Tweet to twitter https://github.com/marketplace/actions/tweet-to-twitter
      - name: Send Tweet Action
        uses: ethomson/send-tweet-action@v1.0.0
        with:
          status: Test Tweet
          consumer-key: ${{ secrets.API_KEY }}
          consumer-secret: ${{ secrets.API_KEY_SECRET }}
          access-token: ${{ secrets.ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.ACCESS_TOKEN_SECRET }}
          