name: create Verkehrszeichen

on:
  push:
    paths:
      - "Verkehrszeichen/**"

jobs:
  # creates texured .obj files and creates a release
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Install Blender
      - name: Install Blender
        run: sudo snap install blender --classic
      # Export .obj from .blend
      - name: Blend > OBJ
        run: blender --background --python utilities/scripts/exportOBJ_Verkehrszeichen.py
      # Create individual Sign .obj from blank type .obj
      - name: Make Signs
        run: python utilities/scripts/retextureOBJ_Verkehrszeichen.py
      # render thumbnails
      - name: render thumbnails
        run: blender --background --python utilities/scripts/renderThumbnail_Verkehrszeichen.py
      # commit changes
      - name: commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push

  
