name: create Verkehrszeichen

on:
  workflow_dispatch:

jobs:
  # creates texured .obj files and creates a release
  defaultAction:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Install Blender
      - name: Install Blender
        run: sudo snap install blender --classic
      # install gitpython
      - name: install gitpython
        run: pip install gitpython
      # Export .obj from .blend
      - name: Blend > OBJ
        run: blender --background --python utilities/scripts/exportOBJ_Verkehrszeichen.py
      # Create individual Sign .obj from blank type .obj
      - name: retextureBlanks
        run: python utilities/scripts/retextureOBJ_Verkehrszeichen.py
      # render thumbnails
      - name: render thumbnails
        run: blender --background --python utilities/scripts/renderThumbnail_Verkehrszeichen.py
      # create Readme
      - name: create Readme
        run: python utilities/scripts/createReadme_Verkehrszeichen.py
      # commit changes
      - name: commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add .
          git commit -m "generated"
          git push

  
